### ISSUE TITLE
doesn't work when spark on yarn

### ISSUE THREAD

**Issue by gnuhpc** [ibmruntimes/spelk#1]
Task failed with this sink, but same job worked when switched to console sink.

local mode also has no exception. Only on yarn mode didnt work out.

17/05/09 10:51:50 INFO BlockManagerMaster: Removal of executor 3 requested
17/05/09 10:51:50 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asked to remove non-existent executor 3
17/05/09 10:51:50 INFO BlockManagerMasterEndpoint: Trying to remove executor 3 from BlockManagerMaster.
17/05/09 10:51:50 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked as failed: container_e30_1494223133661_0026_02_000006 on host: hadoop3. Exit status: 1. Diagnostics: Exception from container-launch.
Container id: container_e30_1494223133661_0026_02_000006
Exit code: 1
Stack trace: org.apache.hadoop.yarn.server.nodemanager.containermanager.runtime.ContainerExecutionException: Launch container failed
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DefaultLinuxContainerRuntime.launchContainer(DefaultLinuxContainerRuntime.java:109)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DelegatingLinuxContainerRuntime.launchContainer(DelegatingLinuxContainerRuntime.java:89)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:392)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:317)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is gnuhpc
main : requested yarn user is gnuhpc
Getting exit code file...
Creating script paths...
Writing pid file...
Writing to tmp file /hadoop/yarn/local/nmPrivate/application_1494223133661_0026/container_e30_1494223133661_0026_02_000006/container_e30_1494223133661_0026_02_000006.pid.tmp
Writing to cgroup task files...
Creating local dirs...
Launching container...
Getting exit code file...
Creating script paths...

Container exited with a non-zero exit code 1

**Comment by gnuhpc** [comment]
Executor Log as below:

> 17/05/09 10:51:36 ERROR MetricsSystem: Sink class org.apache.spark.elk.metrics.sink.ElasticsearchSink cannot be instantiated
> Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1713)
> 	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:284)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.elk.metrics.sink.ElasticsearchSink
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at org.apache.spark.util.Utils$.classForName(Utils.scala:229)
> 	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:198)
> 	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:194)
> 	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
> 	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
> 	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
> 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
> 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
> 	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:194)
> 	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:102)
> 	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:364)
> 	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:200)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:223)
> 	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:67)
> 	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:66)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
> 	... 4 more
> 


It's weird that I have already upload the jar as below.

hadoop1:/usr/share/spark-2.1.0-bin-hadoop2.7 # bin/spark-submit --jars /root/app/spelk-0.1.0.jar  --master yarn --class org.apache.spark.examples.SparkPi  examples/jars/spark-examples_2.11-2.1.0.jar 100

**Comment by gnuhpc** [comment]
After copying the spelk.jar to $SPARK_HOME/jars,  it finally worked. Close this issue
